site_name: Sitekick Remastered
repo_url: https://github.com/SitekickRemastered/Web
repo_name: SitekickRemastered/Web
site_url: https://sitekickremastered.com/
dev_addr: '0.0.0.0:8014'
docs_dir: docs
copyright: Sitekick Remastered is in no way affiliated with YTV Canada, Inc. and/or Corus Entertainment, Inc. Sitekick Remastered is a completely free game, containing no advertisements, subscriptions, microtransactions, or any other form of monetization.
nav:
  - Home: index.md
  - Download: /download/
  - Discord: http://discord.sitekickremastered.com/
  - Help: /help/
  - News: /blog/
theme:
  icon:
    repo: fontawesome/brands/github
  logo: images/misc/logo.svg
  favicon: /images/ico/favicon.ico
  palette:
    # Light Mode
      scheme: default
      primary: custom
      accent: custom
  name: material
  custom_dir: overrides
  features:
    - announce.dismiss
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - navigation.top
    - search.suggest
    - content.tabs.link
    - content.tabs.annotation
    - content.code.copy
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - toc:
      toc_depth: 3

# Custom Homepage Elements
home_cover_image: images/misc/appicon.png
home_tagline: What is Sitekick Remastered?
home_description: |
  Sitekick, an online game developed for YTV.com in 2003, was discontinued in 2015 due to legacy code issues. Sitekick Remastered seeks to both preserve its assets and knowledge and create a new, enhanced version of the game.<br><br>Produced by fans, for fans. Sitekick Remastered is a completely free game, containing no advertisements, subscriptions, microtransactions, or any other form of monetization.  <br><br><b>Sitekick Remastered is <u>in no way affiliated</u> with YTV Canada, Inc. and/or Corus Entertainment, Inc.</b>

# Gradient Color
#home_gradient_hsla: hsla(53, 87%, 51%,1)

# Custom Homepage Button(s)
home_button1_name: Play now
home_button1_url: /download/
home_button1_theme: md-button
home_button1_icon: 
home_button1_blurb: |
  Sitekick Remastered is available for Android, Windows, and Xbox.

home_button2_name: Join us on Discord
home_button2_url: https://discord.sitekickremastered.com/
home_button2_theme: md-button
home_button2_icon: 
home_button2_blurb: |
  Chat and Trade with over 900 other players on our official Discord server.


# Homepage Code Execution
#home_execute_js: | # Javascript to execute when accessing the homepage
#  console.log("This is an example!");

plugins:
  - blog
  - search

extra:
  generator: false
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.sitekickremastered.com
    - icon: fontawesome/brands/github
      link: https://github.com/SitekickRemastered/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/sitekickremastered/
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/SitekickGame
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCZQ0gBa3SbxwfQ5zp4029PQ
  tags:
    tag: identifier
extra_css:
  - stylesheets/extra.css