site_name: Sitekick Remastered
repo_url: https://github.com/SitekickRemastered/Web
repo_name: SitekickRemastered/Web
edit_uri: edit/main/docs/
site_url: https://sitekickremastered.com/
dev_addr: '0.0.0.0:8014'
docs_dir: docs
copyright: Sitekick Remastered is in no way affiliated with YTV Canada, Inc. and/or Corus Entertainment, Inc. Sitekick Remastered is a completely free game, containing no advertisements, subscriptions, microtransactions, or any other form of monetization.
nav:
  - Home: index.md
  - Download: download.md
  - Discord: http://discord.sitekickremastered.com/
  - News: /blog/
  - Wiki:
      - Home: wiki/Sitekick_Wiki.md
      - Development:
          - Changelog: wiki/development/changelog.md
          - Exporting Chips: wiki/development/exporting_chips.md
          - Join the Team: wiki/development/join_the_team.md
      - Guides & FAQ:
          - Contact us: legal/contact_us.md
          - Guides:
              - Downloading Sitekick Remastered: wiki/guides/downloading.md
              - Linking with Discord: wiki/guides/discord.md
              - Registration & Verification: wiki/guides/registration.md
              - SitePic Discord Bot: wiki/guides/sitepic.md
              - What is a Sitekick?: wiki/guides/what_is_a_sitekick.md
          - How to Play:
              - Change Password: wiki/guides/change_password.md
              - Customizing Your Sitekick: wiki/guides/customization.md
              - Delete Account: account/delete_account.md
              - Leveling Up: wiki/guides/experience.md
              - Obtaining Chips: wiki/guides/obtaining_chips.md
              - SK-TV: wiki/guides/sk-tv.md
              - The Chipendium: wiki/chipendium/chipendium.md
              - Trading: wiki/guides/trading.md
              - What is a Sitekick?: wiki/guides/what_is_a_sitekick.md
          - Rules: wiki/rules.md
          - Suggestions & Bug Reports: wiki/guides/suggestions_bug_reports.md
      - Sitekick:
          - Chipendium:
              - Overview: wiki/chipendium/chipendium.md
              - 0001-1000:
                  - 0001-0100: wiki/chipendium/0001-0100.md
                  - 0101-0200: wiki/chipendium/0101-0200.md
                  - 0201-0300: wiki/chipendium/0201-0300.md
                  - 0301-0400: wiki/chipendium/0301-0400.md
                  - 0401-0500: wiki/chipendium/0401-0500.md
                  - 0501-0600: wiki/chipendium/0501-0600.md
                  - 0601-0700: wiki/chipendium/0601-0700.md
                  - 0701-0800: wiki/chipendium/0701-0800.md
                  - 0801-0900: wiki/chipendium/0801-0900.md
                  - 0901-1000: wiki/chipendium/0901-1000.md
              - 1001-2000:
                  - 1001-1100: wiki/chipendium/1001-1100.md
          - DACE: wiki/sitekick/DACE/dace.md
          - Games:
              - Kablooey Flew Throughy: wiki/sitekick/games/kablooey_flew_throughy.md
              - They Came for the Ooze: wiki/sitekick/games/they_came_for_the_ooze.md
          - Lore:
              - "Sitekick: Indefinite Closure": legacy/indefinite_closure.md
              - Characters:
                  - Authicer: wiki/sitekick/lore/characters/authicer.md
                  - Dr. Frantic: wiki/sitekick/lore/characters/dr_frantic.md
                  - Hamster: wiki/sitekick/lore/characters/hamster.md
                  - Kablooey: wiki/sitekick/lore/characters/kablooey.md
                  - Paul: wiki/sitekick/lore/characters/paul.md
                  - SitePic: wiki/sitekick/lore/characters/sitepic.md
              - Ooze: wiki/sitekick/lore/ooze.md
              - The Chip Creator: wiki/sitekick/lore/the_chip_creator.md
              - YAP! Industries: wiki/sitekick/lore/yap.md
          - Players:
              - Robeyblade: wiki/sitekick/players/Robeyblade.md
      - Download: download.md
      - Metrics: wiki/metrics.md

theme:
  icon:
    repo: fontawesome/brands/github
  logo: images/misc/logo.svg
  favicon: /images/ico/favicon.ico
  palette:
    # Light Mode
      scheme: default
      primary: custom
      accent: custom
  name: material
  custom_dir: overrides
  features:
    - content.action.edit
    - content.action.view
    - announce.dismiss
    #- navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.top
    - navigation.instant
    - navigation.indexes
    #- navigation.instant.prefetch
    - navigation.tracking
    - search.suggest
    - content.tabs.link
    - content.tabs.annotation
    - content.code.copy
    - toc.follow
   
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - tables
  - toc:
      toc_depth: 3

# Custom Homepage Elements
home_cover_image: images/misc/appicon.png
home_tagline: What is Sitekick Remastered?
home_description: |
  Sitekick, an online game developed for YTV.com in 2003, was discontinued in 2015 due to legacy code issues. Sitekick Remastered seeks to both preserve its assets and knowledge and create a new, enhanced version of the game.<br><br>Produced by fans, for fans. Sitekick Remastered is a completely free game, containing no advertisements, subscriptions, microtransactions, or any other form of monetization.  <br><br><b>Sitekick Remastered is <u>in no way affiliated</u> with YTV Canada, Inc. and/or Corus Entertainment, Inc.</b>

# Gradient Color
#home_gradient_hsla: hsla(53, 87%, 51%,1)

# Custom Homepage Button(s)
home_button1_name: Play now
home_button1_url: download
home_button1_theme: md-button
home_button1_icon: 
home_button1_blurb: |
  Sitekick Remastered is available for Android, Windows, and Xbox.

home_button2_name: Join us on Discord
home_button2_url: https://discord.sitekickremastered.com/
home_button2_theme: md-button
home_button2_icon: 
home_button2_blurb: |
  Chat and Trade with over 900 other players on our official Discord server.


# Homepage Code Execution
#home_execute_js: | # Javascript to execute when accessing the homepage
#  console.log("This is an example!");

plugins:
  - blog
  - search
  - exclude-search:
      exclude:
        - account/*
        - legal/*
        - email/*
        - images/*

extra:
  generator: false
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.sitekickremastered.com
    - icon: fontawesome/brands/github
      link: https://github.com/SitekickRemastered/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/sitekickremastered/
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/SitekickGame
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCZQ0gBa3SbxwfQ5zp4029PQ
  tags:
    tag: identifier
extra_css:
  - stylesheets/extra.css